import {
  FileMetadata,
  Comment,
  Post,
  Blog,
  UserSession,
  PostReaction,
  PostReactionCounts,
  CommentReaction,
  CommentReactionCounts,
  QuizAnswer,
  QuizGame,
  QuizQuestion,
  QuizPlayerProgress,
  QuizCorrectAnswer,
  CurrentGameQuestion,
  BlogImage,
  PostImage,
} from '../..';
import { Subscription } from '../features/blogs/domain/entities/blog-subscription.entity';
import { TelegramMetaUser } from '../features/integrations/domain/entities/telegram-meta-user.entity';

export const entities = [
  TelegramMetaUser,
  Subscription,
  PostImage,
  BlogImage,
  FileMetadata,
  Comment,
  Post,
  Blog,
  UserSession,
  PostReaction,
  PostReactionCounts,
  CommentReaction,
  CommentReactionCounts,
  QuizAnswer,
  QuizGame,
  QuizQuestion,
  QuizPlayerProgress,
  QuizCorrectAnswer,
  CurrentGameQuestion,
];
