import {
  Blog,
  BlogImage,
  Comment,
  CommentReaction,
  CommentReactionCounts,
  CurrentGameQuestion,
  FileMetadata,
  Post,
  PostImage,
  PostReaction,
  PostReactionCounts,
  QuizAnswer,
  QuizCorrectAnswer,
  QuizGame,
  QuizPlayerProgress,
  QuizQuestion,
  UserSession,
} from '../..';
import { BlogNotifySubscription } from '../features/blogs/domain/entities/blog-subscription.entity';

export const entities = [
  BlogNotifySubscription,
  PostImage,
  BlogImage,
  FileMetadata,
  Comment,
  Post,
  Blog,
  UserSession,
  PostReaction,
  PostReactionCounts,
  CommentReaction,
  CommentReactionCounts,
  QuizAnswer,
  QuizGame,
  QuizQuestion,
  QuizPlayerProgress,
  QuizCorrectAnswer,
  CurrentGameQuestion,
];
