import {
  TemporaryUserAccount,
  Comment,
  Blog,
  CommentReaction,
  CommentReactionCounts,
  Post,
  PostReaction,
  PostReactionCounts,
  UserSession,
  QuizGame,
  QuizQuestion,
  QuizAnswer,
  QuizPlayerProgress,
  CurrentGameQuestion,
  QuizCorrectAnswer,
} from '.';

export const entities = [
  TemporaryUserAccount,
  Comment,
  Post,
  Blog,
  UserSession,
  PostReaction,
  PostReactionCounts,
  CommentReaction,
  CommentReactionCounts,
  QuizAnswer,
  QuizGame,
  QuizQuestion,
  QuizPlayerProgress,
  QuizCorrectAnswer,
  CurrentGameQuestion,
];
